__name__ = 'yolog'
__version__ = '0.3'
__description__ = 'Beautify your Git Logs !'
__url__ = 'https://www.github.com/karandesai-96/yolog'
__author__ = 'Karan Desai'
__email__ = 'karandesai281196@gmail.com'
__license__ = 'MIT'
